- name: Playbook dédié à l'installation d'un socle de développement sur distribution CentOS.
  hosts: localhost
  connection: local
  vars_prompt:
    - name: "user"
      private: no
      prompt: "Compte utilisateur à créer"
    - name: "password"
      prompt: "Mot de passe du compte a creer"
      private: yes
      encrypt: "sha512_crypt"
      salt_size: 7
  tasks:
  - name: Mise à jour du système.
    yum: name=* state=latest
  - name: Installation des paquets nécessaires au bon fonctionnement du bureau.
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - firefox
      - vim
      - "@^gnome-desktop-environment"
      - gdm
  - name: Installation des paquets nécessaires au développement & présents dans les répos officiels (PHP5 & MySQL en fait...).
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - php-5.4.16-43.el7_4.1
      - mariadb-server-5.5.56-2.el7
      - mariadb-5.5.56-2.el7
      - java-1.7.0-openjdk
  - name: Récupération du RPM elasticsearch
    command: wget -O /tmp/elasticsearch.rpm https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.2.rpm
  - name: Installation du RPM elasticsearch
    yum:
      name: /tmp/elasticsearch.rpm
      state: present
  - name: "Création de l'utilisateur {{ user }}."
    user:
      name: "{{ user }}"
      comment: "Utilisateur créé automatiquement par ansible."
      shell: /bin/bash
      state: present
      password: "{{ password }}"
      createhome: yes
      update_password: always
  - name: Ajout des repos un peu tordus pour accéder à PHP7.1 & redis.
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - centos-release-scl.noarch
      - epel-release.noarch
  - name: Installation de PHP7.1 et des modules nécessaires.
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - rh-php71
      - rh-php71-php
      - rh-php71-php-fpm
      - rh-php71-php-cli
  - name: Ajout de PHP7.1 au PATH
    file:
      src: /opt/rh/rh-php71/root/usr/bin/php
      dest: /usr/bin/php71
      owner: root
      group: root
      state: link
  - name: Installation de redis
    yum:
      name: redis
      state: present
  - name: Installation des paquets nécessaires à la compilation des extensions VirtualBox
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - dkms
      - kernel-devel
      - bzip2
      - gcc
      - make
  - name: Téléchargement de l'ISO
    command: wget -O /tmp/additions.iso "http://download.virtualbox.org/virtualbox/{{ vb_version }}/VBoxGuestAdditions_{{ vb_version }}.iso"
  - name: Montage de l'ISO récemment téléchargée.
    mount:
      src: /tmp/additions.iso
      path: /media/additions
      fstype: iso9660
      opts: noauto
      state: mounted
  - name: Installation des additions.
    command: /media/additions/VBoxLinuxAdditions.run
    


  - name: Démarrage & Activation des services.
    service:
      enabled: yes
      name: "{{ item }}"
      state: started
    with_items:
#      - gdm
      - mariadb
      - elasticsearch
      - redis
