- name: Playbook dédié à l'installation d'un socle de développement sur distribution CentOS.
  hosts: localhost
  connection: local
  vars_prompt:
    - name: "user"
      private: no
      prompt: "Compte utilisateur à créer"
    - name: "password"
      prompt: "Mot de passe du compte a creer"
      private: yes
      encrypt: "sha512_crypt"
      salt_size: 7
    - name: "vb_version"
      prompt: "Version de VirtualBox pour laquelle télécharger les additions"
      private: no
      default: 5.2.8
    - name: "ac_path"
      prompt: "Emplacement dans lequel récupérer les autorités de certification internes au format *.cer"
      private: no
      default: /tmp
  tasks:
  - name: Ajout des repos un peu tordus pour accéder à PHP7.1 & redis.
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - centos-release-scl.noarch
      - epel-release.noarch
  - name: Mise à jour du système.
    yum: name=* state=latest
  - name: Récupération du RPM elasticsearch
    command: curl -O /tmp/elasticsearch.rpm https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.2.rpm
  - name: Installation des paquets nécessaires.
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - firefox
      - vim
      - "@^gnome-desktop-environment"
      - gdm
      - php-5.4.16-43.el7_4.1
      - mariadb-server-5.5.56-2.el7
      - mariadb-5.5.56-2.el7
      - java-1.7.0-openjdk
      - /tmp/elasticsearch.rpm
      - rh-php71
      - rh-php71-php
      - rh-php71-php-fpm
      - rh-php71-php-cli
      - redis
      - dkms
      - kernel-devel
      - bzip2
      - gcc
      - make
  - name: Ajout de PHP7.1 au PATH
    file:
      src: /opt/rh/rh-php71/root/usr/bin/php
      dest: /usr/bin/php71
      owner: root
      group: root
      state: link
  - name: Téléchargement de l'ISO VBoxGuestAdditions
    command: curl -O /tmp/additions.iso "http://download.virtualbox.org/virtualbox/{{ vb_version }}/VBoxGuestAdditions_{{ vb_version }}.iso"
  - name: Montage de l'ISO VBoxGuestAdditions.
    mount:
      src: /tmp/additions.iso
      path: /media/additions
      fstype: iso9660
      opts: noauto
      state: mounted
  - name: Installation des additions.
    command: /media/additions/VBoxLinuxAdditions.run
  - name: "Création de l'utilisateur {{ user }}."
    user:
      name: "{{ user }}"
      comment: "Utilisateur créé automatiquement par ansible."
      groups: vboxsf
      shell: /bin/bash
      state: present
      password: "{{ password }}"
      createhome: yes
      update_password: always
  - name: Déploiement de la chaine de certification interne au Groupe.
    copy:
      src: "{{ item }}"
      dest: /etc/pki/ca-trust/source/anchors/
    with_fileglob:
      - "/{{ ac_path }}/*.cer"
  - name: Ajout des certificats au keystore.
    command: update-ca-trust
  - name: Démarrage & Activation des services.
    service:
      enabled: yes
      name: "{{ item }}"
      state: started
    with_items:
      - gdm
      - mariadb
      - elasticsearch
      - redis
